# Generated by Django 4.1.2 on 2022-10-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_alter_user_primary_calendar"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="from_watch",
            field=models.BooleanField(default=False),
        ),
    ]
