# Generated by Django 4.1.2 on 2022-10-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0004_event_from_watch"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="calendars",
            field=models.ManyToManyField(related_name="events", to="audit.calendar"),
        ),
    ]
