# Generated by Django 4.1.2 on 2022-10-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0005_event_calendars"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="all_day",
            field=models.BooleanField(default=False),
        ),
    ]
