# Generated by Django 4.1.2 on 2022-10-10 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0006_event_all_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchChannel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("resource_id", models.CharField(max_length=255)),
                ("expiration", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="calendar",
            name="channel",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="audit.watchchannel",
            ),
        ),
    ]
