# Generated by Django 4.1.2 on 2022-10-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0009_calendar_sync_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="summary",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
